[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "DSC_Python_Project"
requires-python = ">=3.12"
version = "1.0.0"
description = "Pipeline replication and implementation"
authors = [
    { name = "Don Enrico Esteve", ID = "P9550217B", email = "donenrico.esteve@live.biu.ac.il" },
    { name = "Elizabeth Vaisman", ID = "318775277", email = "elizabeth.vaisman@live.biu.ac.il" },
]
license = { text = "CC0 1.0 Universal" }
keywords = ["data science", "python", "pipeline"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: CC0 1.0 Universal",
    "Operating System :: OS Independent"
]
[project.urls]
"Repository" = "https://github.com/DonEnricoEsteve/Data_Science_Project.git"
"Replicated Files" = "https://drive.google.com/drive/folders/12HLqUYrPtiYSf5Ni7tTC4XWkFPLKYR55?usp=sharing"