# Import necessary libraries
import pytest
from conftest import *  # Just imported it manually to ensure

### ===== Test Valid Inputs ===== ###
@pytest.mark.parametrize("sub_idx", [0])  
def test_plot_forward_model_valid(sub_idx):
    plot_forward_model(sub_idx=sub_idx)

    # Check if a plot was generated by verifying the current figure
    assert plt.gcf(), "No figure was generated."

### ===== Test One Invalid Input ===== ###
def test_plot_forward_model_invalid_sub_idx():
    with pytest.raises(IndexError):
        plot_forward_model(sub_idx=99)  # Invalid subject index